trigger:
  - main

variables:
  DOCKER_NAMESPACE: nexusameer
  TAG: $(Build.BuildId)

stages:
- stage: Build
  displayName: 'Build and Push Images'
  jobs:
  - job: BuildAndPush
    displayName: 'Build and Push Services'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: 'Build and Push Vote App'
      inputs:
        containerRegistry: 'docker-connection'
        repository: '$(DOCKER_NAMESPACE)/voting-app-vote'
        command: 'buildAndPush'
        Dockerfile: '**/vote/Dockerfile'
        tags: |
          $(TAG)
          latest

    - task: Docker@2
      displayName: 'Build and Push Result App'
      inputs:
        containerRegistry: 'docker-connection'
        repository: '$(DOCKER_NAMESPACE)/voting-app-result'
        command: 'buildAndPush'
        Dockerfile: '**/result/Dockerfile'
        tags: |
          $(TAG)
          latest

    - task: Docker@2
      displayName: 'Build and Push Worker App'
      inputs:
        containerRegistry: 'docker-connection'
        repository: '$(DOCKER_NAMESPACE)/voting-app-worker'
        command: 'buildAndPush'
        Dockerfile: '**/worker/Dockerfile'
        tags: |
          $(TAG)
          latest
