trigger:
  - main

stages:
- stage: Deploy
  displayName: 'Deploy to AKS'
  jobs:
  - deployment: Deploy
    displayName: 'Deploying Services to AKS'
    pool:
      vmImage: 'ubuntu-latest'
    environment: 'production'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self  # Ensures repo is fully cloned
            persistCredentials: true
            clean: true

          - script: ls -R $(Build.SourcesDirectory)  # Debugging step
            displayName: 'Debug: List all files in working directory'

          - task: KubernetesManifest@0
            displayName: 'Deploy Kubernetes Manifests'
            inputs:
              action: 'deploy'
              kubernetesServiceConnection: 'kubeCluster-connection'
              namespace: 'default'
              manifests: |
                $(Build.SourcesDirectory)/k8s-specifications/db-deployment.yaml
                $(Build.SourcesDirectory)/k8s-specifications/db-service.yaml
                $(Build.SourcesDirectory)/k8s-specifications/redis-deployment.yaml
                $(Build.SourcesDirectory)/k8s-specifications/redis-service.yaml
                $(Build.SourcesDirectory)/k8s-specifications/result-deployment.yaml
                $(Build.SourcesDirectory)/k8s-specifications/result-service.yaml
                $(Build.SourcesDirectory)/k8s-specifications/vote-deployment.yaml
                $(Build.SourcesDirectory)/k8s-specifications/vote-service.yaml
                $(Build.SourcesDirectory)/k8s-specifications/worker-deployment.yaml
              imagePullSecrets: 'docker-connection'
